name: ZeldaChickens
main: com.icomeinpieces.ZeldaChickens.ZeldaChickens
version: 1.0
description: Makes chickens behave like the chickens on Zelda games. Kill one and a bunch come from the skies to attack you.
author: icomeinpieces